CREATE TABLE IF NOT EXISTS account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance_food DECIMAL(12, 2)                          NOT NULL,
    balance_meal DECIMAL(12, 2)                          NOT NULL,
    balance_cash DECIMAL(12, 2)                          NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id BIGINT                                  NOT NULL,
    amount     DECIMAL(10, 2)                          NOT NULL,
    merchant   VARCHAR(255)                            NOT NULL,
    mcc        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ;