CREATE TABLE IF NOT EXISTS merchant
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(255)                            not null,
    mcc     varchar(4)                              not null,
    CONSTRAINT pk_merchant PRIMARY KEY (id),
    CONSTRAINT uk_merchant UNIQUE (name)
);